# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ppc64le/ubuntu:14.04

WORKDIR /root

ARG DEBIAN_FRONTEND=noninteractive

ENV AT_VERSION 10.0

RUN apt-get update \
    && apt-get install -y apt-utils \
    && apt-get install -y wget man-db \
    && wget ftp://ftp.unicamp.br/pub/linuxpatch/toolchain/at/ubuntu/dists/trusty/6976a827.gpg.key \
    && apt-key add 6976a827.gpg.key \
    && rm -f 6976a827.gpg.key \
    && echo "deb ftp://ftp.unicamp.br/pub/linuxpatch/toolchain/at/ubuntu trusty at${AT_VERSION}" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y advance-toolchain-at${AT_VERSION}-runtime advance-toolchain-at${AT_VERSION}-mcore-libs

ENV PATH /opt/at${AT_VERSION}/bin:$PATH

CMD ["/bin/bash"]
