# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG UBUNTU_RELEASE=xenial

FROM ppc64le/ubuntu:${UBUNTU_RELEASE}

ARG UBUNTU_RELEASE=xenial

WORKDIR /root

ENV DEBIAN_FRONTEND=noninteractive

RUN [ -n "$HTTP_PROXY" ] && echo Acquire::http::proxy '"'$HTTP_PROXY'";' >> /etc/apt/apt.conf.d/http_proxy || :
RUN [ -n "$HTTPS_PROXY" ] && echo Acquire::https::proxy '"'$HTTPS_PROXY'";' >> /etc/apt/apt.conf.d/https_proxy || :
RUN [ -n "$FTP_PROXY" ] && echo Acquire::ftp::proxy '"'$FTP_PROXY'";' >> /etc/apt/apt.conf.d/ftp_proxy || :

# Configure apt to nicely install packages
RUN apt-get update \
    && apt-get install -y apt-utils \
        autoconf automake bison byacc ccache cscope ctags curl flex \
        elfutils libtool libstdc++-4.8-dev m4 make man-db \
    && apt-get clean

ARG AT_VERSION=10.0

ENV http_proxy $HTTP_PROXY

RUN curl http://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu/dists/trusty/6976a827.gpg.key | apt-key add - \
    && echo "deb http://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu ${UBUNTU_RELEASE} at${AT_VERSION}" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y advance-toolchain-at${AT_VERSION}-runtime advance-toolchain-at${AT_VERSION}-devel \
        advance-toolchain-at${AT_VERSION}-perf advance-toolchain-at${AT_VERSION}-mcore-libs

ENV PATH /opt/at${AT_VERSION}/bin:$PATH

CMD ["/bin/bash"]
