# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG ARCH
ARG DISTRO_NAME
ARG DISTRO_NICK

FROM ${ARCH}/${DISTRO_NAME}:${DISTRO_NICK}
ARG AT_VERSION
ARG DISTRO_NAME
ARG DISTRO_NICK
ARG EXTRA
ARG MINOR
ARG REPO

WORKDIR /root

ENV DEBIAN_FRONTEND noninteractive

RUN [ -n "$HTTP_PROXY" ] && echo Acquire::http::proxy '"'$HTTP_PROXY'";' >> /etc/apt/apt.conf.d/http_proxy || :
RUN [ -n "$HTTPS_PROXY" ] && echo Acquire::https::proxy '"'$HTTPS_PROXY'";' >> /etc/apt/apt.conf.d/https_proxy || :
RUN [ -n "$FTP_PROXY" ] && echo Acquire::ftp::proxy '"'$FTP_PROXY'";' >> /etc/apt/apt.conf.d/ftp_proxy || :

RUN apt-get update \
    && apt-get install -y apt-utils curl gnupg \
    && apt-get clean

ENV http_proxy $HTTP_PROXY

RUN curl -s ${REPO}/${DISTRO_NAME}/dists/${DISTRO_NICK}/6976a827.gpg.key | apt-key add - \
    && echo "deb ${REPO}/${DISTRO_NAME} ${DISTRO_NICK} at${AT_VERSION}" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y advance-toolchain-at${AT_VERSION}${EXTRA}-runtime \
        advance-toolchain-at${AT_VERSION}${EXTRA}-mcore-libs \
        advance-toolchain-at${AT_VERSION}${EXTRA}-devel \
        advance-toolchain-at${AT_VERSION}${EXTRA}-perf

RUN ln -sf /opt/at${AT_VERSION}${MINOR}${EXTRA}/lib64/ld64.so.2 /lib64/ld64.so.2
RUN ln -sf /opt/at${AT_VERSION}${MINOR}${EXTRA}/sbin/ldconfig /sbin/ldconfig

ENV PATH /opt/at${AT_VERSION}${MINOR}${EXTRA}/bin:$PATH

CMD ["/bin/bash"]
